import { Button, Htag, Paragraph } from "@/components";

import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Htag tag="h2">Text</Htag>
        <div style={{ marginBottom: "10px", display: "flex", justifyContent: "center" }}>
          <Button>Button-1</Button>
        </div>
        <div style={{ marginBottom: "10px", display: "flex", justifyContent: "center" }}>
          <Button appearance="ghost" arrow="down">
            Button-2
          </Button>
        </div>
        <div style={{ marginBottom: "10px", display: "flex", justifyContent: "center" }}>
          <Paragraph>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Laboriosam sed officiis maiores sapiente nulla ab
            dignissimos facilis nemo! Asperiores, dolore debitis magni iure ad iusto minima eaque blanditiis sint
            commodi.
          </Paragraph>
        </div>
      </div>
    </>
  );
}
